language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=PSR1,PSR2 src test
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/coveralls -v
