language: php
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/php-coveralls -v

allow_failures:
  - php: nightly
