version: '3'

services:
  php:
    build: ./docker/image/${IMAGE:-php_8_1}
    volumes:
      - .:/app
      - ${COMPOSER_HOME:-$HOME/.composer}:/tmp
    networks:
      - app

networks:
  app:
    driver: bridge
