services:
  php:
    build: ./docker/image/${IMAGE:-php_8_3}
    volumes:
      - .:/app
      - ${COMPOSER_HOME:-$HOME/.composer}:/tmp
    networks:
      - app
    environment:
      - XDEBUG_CONFIG
      - XDEBUG_MODE
      - XDEBUG_TRIGGER
      - PHP_IDE_CONFIG
      - COMPOSER_ROOT_VERSION=dev-master

networks:
  app:
    driver: bridge
