title: PHP-Textile
url:
slogan: Textile markup language parser for PHP
assets_url: /assets/
description: Textile markup language parser for PHP
sandbox_url: http://php-textile-sandbox.test/
textile_url: https://textile-lang.com/
github_url: https://github.com/textile/php-textile
textile_slogan: Humane web text generator
php_textile_version_minor: 3.6
php_textile_version_latest: 3.6.1
