name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      COMPOSER_HOME: ./.composer

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: Process test reports
        run: make process-reports

      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
