name: Pull Request CI

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      COMPOSER_HOME: ./.composer

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make test
