name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Changelog
        id: changelog
        run: |
          echo "contents<<CHANGELOGEOF" >> $GITHUB_OUTPUT
          sed -e '1,/h2./d' -e '/h2./,$d' CHANGELOG.textile | sed 's/@/`/g' >> $GITHUB_OUTPUT
          echo "CHANGELOGEOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          body: ${{ steps.changelog.outputs.contents }}
